### ISSUE TITLE
pipelines: Add simple hello world example

### ISSUE THREAD

**Issue by nparks-kenzan** [kenzanlabs/capstan#10]
Capstan should ship with a reference pipeline already set-up in spinnaker. 

Said pipeline should not require additional environment set-up; whereas, once capstan completes the creation of the environment the pipeline should be instantly runnable.

**Comment by nparks-kenzan** [comment]
@hiI am going to leave this open even though simple pipeline is merged, but I would like to iterate on the automation

**Comment by hmvidal** [comment]
Initial example pipeline part of release 2018.q3.alpha.pipelines

Automation to be included in a future release

**Comment by nparks-kenzan** [comment]
#39 Will cover the auto install
