### ISSUE TITLE
Unable to find the autogenerated jenkins password

### ISSUE THREAD

**Issue by dwilliams-kenzan** [kenzanlabs/capstan#43]
After setting up capstan, the autogenerated password for jenkins is lost in the scroll back buffer.  Halyard is very noisy and fills the scroll back buffer, losing the jenkins password off the buffer.  Some way to retrieve the jenkins password should be added.  The following are possible suggestions:
* Add the password to a terraform output value so it's printed at the very end.
* Silence Halyard so the scroll back buffer isn't filled with noise.
* Output the password to a file on the local file system, allowing it to be retrieved at a later point in time.

**Comment by nparks-kenzan** [comment]
resolved by different means
